import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import axios from "axios";
import { headers } from "next/headers";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const fetchStore = async () => {
	try {
		const domain = (await headers()).get("host")?.split(":");
		const res = await axios.get(`http://localhost:8000/api/store/theme/${domain ? domain[0] : ""}`);

		return res.data;
	} catch (error) {
		console.log(error);
	}
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const store = await fetchStore();
 	const rootStyle = {
		// ["--color-background" as any]: store.data.theme.backgroud,
		// ["--color-foreground" as any]: store.data.theme.foreground,
		// ["--color-primary" as any]: store.data.theme.accent,
		// ["--border" as any]: store.themeOverrides.border,
	} as React.CSSProperties;
	return (
		<html lang="en" style={rootStyle}>
			<body
				className={`${geistSans.variable} ${geistMono.variable} bg-[var(--color-background)] text-[var(--color-foreground)] antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
